server:
  port: 8786

spring:
  application:
    name: goods
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:phoenix:hb-proxy-pub-wz944wbx5ao116609-master1-001.hbase.rds.aliyuncs.com,hb-proxy-pub-wz944wbx5ao116609-master2-001.hbase.rds.aliyuncs.com,hb-proxy-pub-wz944wbx5ao116609-master3-001.hbase.rds.aliyuncs.com:2181
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    username:
    password:
    druid:
      default-auto-commit: true
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter: stat,wall,log4j
      connection-properties: phoenix.force.index=false
  rabbitmq:
    port: 5672
    password: dooogotsmq
    username: dooogo
    host: 47.106.184.205
  redis:
    database: 0
    host: 47.106.184.205
    port: 6379
    password: dgkj321ff
    saveExpires: 259200   # 3*24*60*60 三天的时间【防止出错，不然都是直接删除】
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
