server:
  port: 8790

spring:
  application:
    name: marketing
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url:  jdbc:phoenix:thin:url=http://47.106.184.205:8765;serialization=PROTOBUF
    driver-class-name: org.apache.phoenix.queryserver.client.Driver
    username:
    password:
    druid:
      default-auto-commit: true
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter: stat,wall,log4j
      connection-properties: phoenix.force.index=false
