server:
  port: 8788

spring:
  application:
    name: yingshi
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:phoenix:hb-proxy-pub-wz99g439bjkv750dg-002.hbase.rds.aliyuncs.com,hb-proxy-pub-wz99g439bjkv750dg-001.hbase.rds.aliyuncs.com,hb-proxy-pub-wz99g439bjkv750dg-003.hbase.rds.aliyuncs.com:2181
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    username:
    password:
    druid:
      default-auto-commit: true
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter: stat,wall,log4j
      connection-properties: phoenix.force.index=false
      
  rabbitmq:
    host: 192.168.153.136  #220.231.216.85
    username: guest
    password: guest
    port: 5672
  mail:
    host: smtp.exmail.qq.com
    username: airflow@dooogo.com
    password: Dgkj889966
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          mail:
            smtp:
              socketFactory:
                class: javax.net.ssl.SSLSocketFactory
                fallback: false
                port: 465
fdfs:
  url: http://220.231.216.162:8989
  
dooogo:
  url: http://smaster.dooogo.com
